# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# See readme file for info about variable group "BlazorServerDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  #- none
  batch: true
  branches:
    include:
      - main
    exclude:
      - '**/*.md'
  paths:
    include:
      - 'logicapps.publish.app/*'

pool:
  vmImage: 'windows-latest'

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-and-website-pipeline-template.yml
  parameters:
    variableGroupName: 'LASPublishDemo'
    folderName: 'logicapps.publish.app'
    projectName: 'logicapps.publish.app'
    webAppName: 'publish'
    environments: ['DEMO']
