# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Website Only
# See ../Docs/Create-Variable-Group.md for info about variable group "BlazorServerDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(Build.DefinitionName).$(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - 'logicapps.publish.app/*'
    exclude: 
      - '**/*.yml'
      - '**/*.bicep'
      - '**/*.md'

pool:
  vmImage: windows-latest

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/website-only-pipeline-template.yml
  parameters:
    variableGroupName: 'LASPublishDemo'
    folderName: 'logicapps.publish.app'
    projectName: 'logicapps.publish.app'
    webAppName: 'publish'
    environments: ['DEMO']
